version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
# hooks:
#   ApplicationStart:
#     - location: /scripts/application_start.sh
#       timeout: 300
#       runas: root
